---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)
library(readr)
```

```{r}
decat_analysis_datav1 <- read_csv("decathalon_cleaned_data.csv")
```

```{r}
class (decat_analysis_datav1)

```


```{r}
names(decat_analysis_datav1)
```

```{r}
#Who had the longest long jump seen in the data?

decat_analysis_datav1 %>% 
  select(names, long_jump) %>% 
  arrange(desc(long_jump)) %>% 
  head(1)
  
  
```
```{r}
#What was the average 100m time in each competition?

decat_analysis_datav1 %>% 
  select (`100_m`, competition) %>% 
  group_by(competition) %>% 
  summarise(avg = mean(`100_m`))
 

```

```{r}
#Who had the highest total points across both competitions?

decat_analysis_datav1 %>% 
  select (names,competition, points) %>% 
  group_by(competition) %>% 
  slice_max(points, n = 1)
  

```

```{r}
#What was the shot-put scores for the top three competitors in each competition?

decat_analysis_datav1 %>% 
  select (names,competition, shot_put) %>% 
  group_by(competition) %>% 
  slice_max(shot_put, n = 3)
```
```{r}
#What was the average points for competitors who ran the 400m 
#in less than 50 seconds vs. those than ran 400m in more than 50 seconds?


more_than_50 <- decat_analysis_datav1 %>% 
  select(names, `400_m`, competition) %>% 
  filter (`400_m` > 50.00) %>% 
  group_by(competition) %>% 
  summarise(avg_more_than_50 = mean(`400_m`))
  
more_than_50

less_than_50 <- decat_analysis_datav1 %>% 
  select(names, `400_m`, competition) %>% 
  filter (`400_m` < 50.00) %>% 
  group_by(competition) %>% 
  summarise(avg_less_than_50 = mean(`400_m`))

less_than_50

full_join(more_than_50, less_than_50)
```

